version: '3.9'

services:
  backend:
    container_name: ngcash_server_backend
    build: ./
    ports:
      - 3001:3001
    working_dir: /app
    depends_on:
      ngcash_db:
        condition: service_healthy
    environment:
      - SERVER_PORT=3001
      - DB_HOST=localhost
      - DB_USER=ngcash
      - DB_PASS=ngcash123
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  ngcash_db:
    container_name: ngcash_database
    image: 'postgres'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ngcash123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5

  
    
